### ISSUE TITLE
Problem with CerboGX

### ISSUE THREAD

**Issue by Kalored** [h4ckst0ck/dbus-solaredge#1]
Cant start the adapter on CerboGX with connected Multiplus ll .
Solarsystem is SE12K with no other modbus connection open.

$/data/dbus-solaredge# python /data/dbus-solaredge/dbus-solaredge.py
2022-06-27 21:27:30,750 - DbusSolarEdge - INFO - Startup, trying connection to Modbus-Server: ModbusTCP 192.168.178.11:1502, UNIT 126
2022-06-27 21:27:30,770 - DbusSolarEdge - INFO - Connected to Modbus Server.
2022-06-27 21:27:30,799 - root - INFO - registered ourselves on D-Bus as com.victronenergy.grid.grid_id00
Traceback (most recent call last):
  File "/data/dbus-solaredge/dbus-solaredge.py", line 326, in <module>
    dbusservice['grid']           = new_service(base, 'grid',           'grid',              0, 0)
  File "/data/dbus-solaredge/dbus-solaredge.py", line 208, in new_service
    log.error('regs.isError: '+regs)
TypeError: can only concatenate str (not "ModbusIOException") to str

**Comment by tomsch1** [comment]
I had the same issue and as q quick hack I am able to run the application by removing the 'regs' from the log.error message.
It is probably somehow possible to get the regs.errorMessage or something similar from this ModbusIOException.

**Comment by h4ckst0ck** [comment]
This should be fixed with the latest commit.
